# Generated by Django 5.2 on 2025-10-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
